# Generated by Django 2.2.4 on 2019-08-05 18:27

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('publication_year', models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1984), books.models.max_value_current_year])),
                ('edition', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.CharField(max_length=255, verbose_name='Title')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
