# Generated by Django 2.2.4 on 2019-08-08 02:56

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(500), books.models.max_value_current_year]),
        ),
    ]
